<a href="https://colab.research.google.com/github/ReasonDuan/machine-learning-code/blob/main/torch-lesson01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Torch 学习脚本

### 基本操作
torch 默认的数据类型为FloatTensor
randn 函数可以随机生成指定维度向量

In [ ]:
import torch
a = torch.randn(2, 3)
a.type()
isinstance(a, torch.FloatTensor)

True

In [ ]:
isinstance(a, torch.cuda.FloatTensor)

False

将数据搬运到GPU上

In [ ]:
a=a.cuda()
isinstance(a, torch.cuda.FloatTensor)

shape获取标量维度

In [ ]:
b = torch.tensor(2.2)
b.shape

torch.Size([])

In [ ]:
torch.randn(3,3)

tensor([[-0.3332,  1.7246,  0.4766],
        [ 0.8593, -1.3052, -0.3515],
        [ 0.8213, -0.7560, -0.3105]])

In [ ]:
torch.normal(mean=torch.full([10],0), std=torch.arange(1, 0, -0.1))

RuntimeError: ignored

In [ ]:
torch.full([2,3],6)

tensor([[6, 6, 6],
        [6, 6, 6]])

In [ ]:
torch.full([2], 5)

tensor([5, 5])

In [ ]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

linspace(a,b, steps=n)从a到b平分n个

In [ ]:
torch.linspace(0,9, steps=10)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
torch.logspace(0, -1, steps=10)

tensor([1.0000, 0.7743, 0.5995, 0.4642, 0.3594, 0.2783, 0.2154, 0.1668, 0.1292,
        0.1000])

randperm(n) 随机生成0到n-1个整数

In [ ]:
torch.randperm(10)

tensor([2, 6, 0, 1, 9, 7, 5, 3, 8, 4])